spring.application.name=employee-security-api

spring.datasource.url=jdbc:postgresql://localhost:5432/springbootdb
spring.datasource.username=postgres
spring.datasource.password=Surjeet@140106

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true