spring.application.name=employee-security-api

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/springbootdb
spring.datasource.username=postgres
spring.datasource.password=Surjeet@140106

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUQXV0aGVudGljYXRpb25UaGF0SXNMb25nRW5vdWdoMTIzNDU2Nzg5MA==
jwt.expiration=3600000